# Generated by Django 3.2.23 on 2024-01-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_newmo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rojo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ca", models.BigIntegerField()),
            ],
        ),
    ]
