# Generated by Django 3.2.23 on 2024-01-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rojo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newmo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaaa', models.BigIntegerField()),
                ('vxx', models.BigIntegerField()),
            ],
        ),
    ]
